baseURL = 'https://luolinlin1201.github.io/Im00_im00/'
languageCode = 'en-us'
title = "00's blog"
theme = 'ananke'

defaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 3
googleAnalytics = ""
enableRobotsTXT = true

[languages]
  [languages.en]
    title = "Linlin's Blog"
    weight = 1
    contentDir = "content/EN"

  [languages.cn]
    title = "琳琳的博客"
    weight = 1
    contentDir = "content/CN"

[params]
  [params.linlin_LinkedIn]
    name = "LinkedIn"
    url = "https://www.linkedin.com/in/linlinluo/"
