title = "Linlin's Blog"
baseURL = "https://luolinlin1201.github.io/Im00_im00/"
languageCode = "en-us"
theme = "ananke"

DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 3 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

[languages]
  [languages.en]
    title = "Linlin's Blog"
    weight = 1
    contentDir = "content/en"
    # languageDirection = 'rtl' for Right-To-Left languages
  [languages.cn]
    title = "琳琳的博客"
    weight = 1
    contentDir = "content/cn"

[params]
  text_color = ""
  author = ""
  favicon = ""
  site_logo = ""
  description = "The last theme you'll ever need. Maybe."
  background_color_class = "bg-black"
  recent_posts_number = 3

[[params.ananke_socials]]
name = "LinkedIn"
url = "https://www.linkedin.com/in/linlinluo/"
