baseURL = 'https://luolinlin1201.github.io/Im00_im00/'
languageCode = 'en-us'
title = "00's blog"
theme = 'ananke'

[[params.linlin_LinkedIn]]
name = "LinkedIn"
url = "https://www.linkedin.com/in/linlinluo/"
