baseURL = 'https://luolinlin1201.github.io/Im00_im00/'
languageCode = 'en-us'
title = "00's blog"
theme = 'ananke'

[params]
  text_color = ""
  author = ""
  favicon = ""
  site_logo = ""
  description = "The last theme you'll ever need. Maybe."
  # choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  cascade = { }
  featured_image = '/images/gohugo-default-sample-hero-image.jpg'
  recent_posts_number = 3
